/**
 * Writes preview copies of the extension pages next to the originals, with the
 * chrome stub injected, so they can be opened in a plain browser tab.
 *
 *   node dev/preview/build.mjs
 *   → src/popup/popup.preview.html?theme=dark&seed=full&page=site
 *
 * Generated next to the source (not in a separate folder) so every relative
 * path in the page keeps working untouched. Both outputs are gitignored.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..');

const PAGES = [
  ['src/popup/popup.html', 'src/popup/popup.preview.html', '../../dev/preview/chrome-stub.js'],
  ['src/options/options.html', 'src/options/options.preview.html', '../../dev/preview/chrome-stub.js']
];

for (const [source, target, stub] of PAGES) {
  const html = readFileSync(join(ROOT, source), 'utf8');
  const marker = '<script src="../shared/site.js"></script>';
  if (!html.includes(marker)) {
    throw new Error(`${source} no longer loads shared/site.js where the preview expects it`);
  }
  const out = html
    .replace('<title>', '<!-- GENERATED by dev/preview/build.mjs — do not edit -->\n<title>')
    .replace(marker, `<script src="${stub}"></script>\n${marker}`);
  writeFileSync(join(ROOT, target), out);
  console.log(`wrote ${target}`);
}
